{
 "title": "sandbox.bio",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "tutorialName",
    "label": "Tutorial IDs",
    "query": "SELECT DISTINCT tutorial\nFROM (\n  SELECT tutorial\n  FROM pings\n  ORDER BY time DESC\n  LIMIT 100\n) t"
   }
  ]
 },
 "panels": [
  { "title": "Watch out for", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('postgres')"
    }
   ]
  },
  {
   "title": "User Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM auth.users"
    }
   ]
  },
  {
   "title": "Users with most storage usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  users.email,\n  COALESCE(pg_column_size(state.env),0) + COALESCE(pg_column_size(state.progress),0) as total_size,\n  COALESCE(pg_column_size(state.env),0) as env_size,\n  COALESCE(pg_column_size(state.progress),0) as progress_size\nFROM public.state\nJOIN auth.users ON auth.users.id = public.state.user_id\nORDER BY total_size DESC\nLIMIT 5"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Pings per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, '1h') as time,\n  COUNT(id) as value\n  -- <your site name field> as metric\nFROM pings\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Page Views per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, '1h') as time,\n  COUNT(id) as value\nFROM logs\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Histogram of minutes spent per step",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH min_runtime AS (\n  SELECT ip, tutorial, $__timeGroup(time, '24h') as time_rounded, time, MIN(time)\n  FROM pings\n  WHERE $__timeFilter(time)\n  GROUP BY ip, tutorial, time\n)\n\nSELECT ABS(extract(epoch from (pings.time - min_runtime.min))) / 60 AS diff\n-- pings.tutorial, pings.step_to, pings.time, min_runtime.min, \n-- , $__timeGroup(pings.time, '24h') AS time_ping, min_runtime.time AS time_min, pings.time AS time_ping2, \nFROM pings\nJOIN min_runtime ON pings.ip = min_runtime.ip AND pings.tutorial = min_runtime.tutorial AND $__timeGroup(pings.time, '24h') = min_runtime.time_rounded\nWHERE extract(epoch from (pings.time - min_runtime.min)) > 0\nAND extract(epoch from (pings.time - min_runtime.min))/60 < 20\n"
    }
   ]
  },
  {
   "title": "Histogram of lesson movement",
   "type": "histogram",
   "description": "* Go to next step: +1\n* Go to prev step: -1\n* Users can also jump multiple lessons using the sidebar TOC",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  step_to - step_from\nFROM\n  pings\nWHERE\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Pings per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, '1d') as time,\n  COUNT(id) as value\nFROM pings\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Page Views per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(time, '1d') as time,\n  COUNT(id) as value\nFROM logs\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  { "title": "Completion rates per lesson", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$tutorialName",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "repeat": "tutorialName",
   "targets": [
    {
     "rawSql": "SELECT\n  lpad(step_to::text, 4, '0'),  -- pad numbers by zeros (Grafana requires x axis to be a string...)\n  COUNT(id) AS value\nFROM\n  pings\nWHERE\n  $__timeFilter(time)\n  AND step_to <> 0\n  AND tutorial = ${tutorialName}\nGROUP BY step_to\nORDER BY step_to ASC\n"
    }
   ]
  }
 ]
}